## Function - Ex - CSV(Comma Separated Value) Data Set Convert into Pandas Data Frame through a Built Function
     * Built In Function - Ex - Print(), input(), len()
     * User Defined - Provide Set of Instruction (Particular Input, Particular Output), We have to Repeat Instruction We will call               through Function Which Reduces Redundancy, Increase Reuseability

## Basic Structure of Function - Declaration - def name(parameters)
                                               "-----> Doc String ----->"
                                               Instruction
                                               return type

In [96]:
def welcome_message(): # No Parameter, No Return Type Function
    print("Hello User")
welcome_message()

Hello User

In [97]:
def welcome_message(user): 
    print(f"Hello {user}")
welcome_message("KutuMia")

Hello KutuMia

## If User Dosen't Give Input

In [98]:
def welcome_message(user = "None"): # Set a Default Value
    print(f"Hello {user}")
welcome_message()

Hello None

## Summation Of Two Number Through Fuction and Return the result

In [99]:
def adder(a,b):
    """
    Add Two Numbers
    a ---> int
    b ---> int
    """
    sum = a + b
    return sum
m = adder(10,30) * 5
print(m)

200

## How String Doc Helps

In [100]:
help(adder) # The Output Will Showing the Details What the Function Does

Help on function adder in module __main__:

adder(a, b)
    Add Two Numbers
    a ---> int
    b ---> int

In [101]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

## Positional Arguments - When You are Passing value to Funcion called Argument, and The value goes in function called parameters
                       Types- 1. Positional
                              2. Keyword

In [102]:
def adder(a,b,c): # a is mapping with - 10, b mapping With - 20, c mapping with - 30 thats called positional arguments 
    print(f"{a},{b},{c}")
adder(10,20,30)

10,20,30

## Variable Sized Positional Arguments

In [103]:
def adder(*args): 
    print(f"{args}")
adder(10,20,30,40)

(10, 20, 30, 40)

In [104]:
def adder(*args): # We can Pass So Many Variables
    for i in args:
        print(f"{i}")  
adder(10,20,30,40)

10
20
30
40

## Keyword Arguments

In [105]:
def adder(a,b,c): 
    print(f"{a},{b},{c}")
adder(a=10, c=20, b=30)

10,30,20

## Variable Sized Keyword Arguments

In [106]:
def adder(**args):
    print(args)
adder(a=10, b=30, c=40, n_estimator=50)

{'a': 10, 'b': 30, 'c': 40, 'n_estimator': 50}

In [107]:
def adder(**args):
    for key,value in args.items():
        print(f"Key : {key} , Value : {value}")     
adder(a=10, b=30, c=40, n_estimator=50)

Key : a , Value : 10
Key : b , Value : 30
Key : c , Value : 40
Key : n_estimator , Value : 50

## Return Type of a Function

In [108]:
def welcome_message(): # No Parameter, No Return Type Function
    print("Hello User")
print(type(welcome_message()))

Hello User
<class 'NoneType'>

In [109]:
def adder(a,b):
    """
    Add Two Numbers
    a ---> int
    b ---> int
    """
    sum = a + b
    return sum
print(type(adder(10,20)))

<class 'int'>

In [110]:
def adder(a,b):
    """
    Add Two Numbers
    a ---> int
    b ---> int
    """
    sum = a + b
    return sum
print(type(adder(10,20.0)))

<class 'float'>

In [111]:
def adder(a,b):
    """
    Add Two Numbers
    a ---> int
    b ---> int
    """
    sum = a + b
    return sum
print(type(adder(10.20,20.20)))

<class 'float'>

In [112]:
def welcome_message(user): 
    return f"Hello {user}"
print(type(welcome_message("KutuMia")))

<class 'str'>

## Return Multiple Value

In [113]:
def adder(a,b):
    return a,b
print(type(adder(10.20,20.20)))

# Unzip
x,y = adder(10.20,20.20)
print(f"{x} , {y}")

<class 'tuple'>
10.2 , 20.2

## for inplace = true , A=[] will be updated by changing in A[] ..no copy, inplace = false means a copy of A=[] will be exist

## Iterator - A List can be accesed by index but a set or dictionary? can't so we can use iterator

In [121]:
s = {10,20,30,40,50} # A Set
s_iter = iter(s)
print(type(s_iter))

print(next(s_iter)) # As Set is not ordered... and can't Access by index
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))

print(f"Again")

for i in s: # internally created iterator...and running untill ending
    print(f"{i}")

<class 'set_iterator'>
50
20
40
10
30
Again
50
20
40
10
30

## Generator - you have a memory 4 GB but Given data set is 10 GB... its not possible to load the data set..the system will crash... we can use chunk... where generator helps or it can be called yield that can pass value by chunk

In [128]:
lst = [x for x in range(500)] # Dataset
#print(lst)

# Chunk
def data_loader(chunk_size,lst):
    for i in range(0, len(lst), chunk_size):
        yield lst[i: i + chunk_size]
x = data_loader(5,lst)
print(type(x))
print(next(x))
print(next(x))

<class 'generator'>
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]

## Lamda - inline and anonymonus.. def: lembda variable a , variable b: Expression, Map and Apply Function

In [135]:
import pandas as pd

df = pd.DataFrame({'temperature(F)': [32,212,98.6,68]})
df
df['temperature(C)'] = df['temperature(F)'].apply(lambda x : (x - 32) * 5 / 9)
print(df)

   temperature(F)  temperature(C)
0            32.0             0.0
1           212.0           100.0
2            98.6            37.0
3            68.0            20.0

In [136]:
import pandas as pd
df = pd.DataFrame({'A' : [1, 2, 3, 4] , 'B' : [5, 6, 7, 8]})
df
df['A'] = df['A'].apply(lambda x : x ** 0.5)
df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [137]:
import pandas as pd
df = pd.DataFrame({'total_spent' : [120, 600, 450, 800]})
df
df['is_high_value'] = df['total_spent'].apply(lambda x : 1 if x > 500 else 0)
df

   total_spent  is_high_value
0          120              0
1          600              1
2          450              0
3          800              1